name: Release package

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  bundle-and-release:
    name: Bundle and release packages
    runs-on: ubuntu-latest
    permissions:
      contents: write # Used to upload the bundled library
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
      - name: Bundle and release the library
        uses: hasnep/bundle-roc-library@main
        with:
          library: package/main.roc # Path to the library's entrypoint
          token: ${{ github.token }}
